name: deploy-client

on:
  push:
    branches: 
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd client && docker build -t drendragon/client .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push drendragon/client
    - uses: digitalocean/action@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save drendragon-ticketing
    - run: kubectl rollout restart deployment client-depl
